export const myCheckbox:string;
export const time:string;
export const checkboxAndTimeContainer:string;
export const mainContainer:string;
export const taskBody:string;
export const subContainer:string;
export const buttonsContainer:string;
export const description:string;
export const title:string;
